### PR TITLE
Add Okapi utility class similar to ZebraCrossing

### PR DESCRIPTION
**Pull request by melloware**

### CODE REVIEW

**Review by turing85 — APPROVED** [review]
It may be beneficial to not validate the exact image data in the tests, but decode the image and verify that it decodes to the expected data. This isn't just for okapi, but for the other sub-projects as well.

**Comment by melloware** [comment]
How do you suggest validating it decodes to the correct image?

**Comment by turing85** [comment]
> How do you suggest validating it decodes to the correct image?

We'd have to look into it. `zxing` comes with the capability to also decode QR codes (see https://github.com/turing85/quarkus-qr/blob/main/src/test/java/de/turing85/qr/code/generator/actor/QrCodeActor.java#L60-L69). We'd need to check if we can cover all relevant cases.

**Comment by melloware** [comment]
yeah i think Okapi has decoders as well.

**Comment by melloware** [comment]
@turing85 another thought i had is technically you could put your Rest Service in this extension and allow it to be exposed with config settings if a user wants to.  Its similar to how Logging Manager works it has the Rest service in it and allows user to expose it to OpenAPI etc.

see: https://github.com/quarkiverse/quarkus-logging-manager

**Comment by turing85** [comment]
> @turing85 another thought i had is technically you could put your Rest Service in this extension and allow it to be exposed with config settings if a user wants to. Its similar to how Logging Manager works it has the Rest service in it and allows user to expose it to OpenAPI etc.
> 
> see: https://github.com/quarkiverse/quarkus-logging-manager

What exactly should we expose there? Endpoints to convert some text to codes?

**Comment by melloware** [comment]
Yeah for example your project exposes this: https://github.com/turing85/quarkus-qr/blob/main/src/main/java/de/turing85/qr/code/generator/QrCodeResource.java

Why not just have that as part of this RunTime and have people say...

```
quarkus.barcode.zxing.rest.enabled=true
quarkus.barcode.zxing.openapi.included=true
```

**Pull request merged**
